Data analytics for bitcon project

Import Libraries
```{r}
#install.packages('xts')
library('xts')
library('lmtest')
library('stargazer')
```

1. Set working directory so R can find and import data files 

```{r}
setwd("~/Documents/ECO 590 - R & Python")

bitcoin_data <- read.csv('Nguyen_Huy_Dataa.csv')

head(bitcoin_data)

```


2. Construct regressions for covariances of bitcoin-SP500, bitcoin-gold, and bitcoin-usd
```{r}
bitcoin_data$VIX_covid <-bitcoin_data$VIX * bitcoin_data$covid
bspy <- lm(cov_bspy ~ VIX + VIX_covid + btc_garch + gg_trend_wrld, data = bitcoin_data)
summary(bspy)
```

Construct regressions for covariances of bitcoin-gold
```{r}
bgld <- lm(cov_bgld ~ VIX + VIX_covid + btc_garch + gg_trend_wrld, data = bitcoin_data)
summary(bgld)
```

Construct regressions for covariances of bitcoin-usd

```{r}
busd <- lm(cov_busd ~ VIX + VIX_covid + btc_garch + gg_trend_wrld, data = bitcoin_data)
summary(busd)
```

3. Construc result table
```{r}
stargazer(bspy, bgld, busd, type = "html", title = 'Regression Result',
          omit.table.layout = "l", out = 'bitcoin.html', model.numbers = FALSE)
```

